python train.py  --model bart --batch_size 8 --accumulation_steps 12 --fold 0 --seed 114 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full 
python train.py  --model bart --batch_size 8 --accumulation_steps 12 --fold 1 --seed 124 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model bart --batch_size 8 --accumulation_steps 12 --fold 2 --seed 134 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model bart --batch_size 8 --accumulation_steps 12 --fold 3 --seed 144 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model bart --batch_size 8 --accumulation_steps 12 --fold 4 --seed 154 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta-large --batch_size 8 --accumulation_steps 12 --fold 0 --seed 64 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full 
python train.py  --model roberta-large --batch_size 8 --accumulation_steps 12 --fold 1 --seed 74 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta-large --batch_size 8 --accumulation_steps 12 --fold 2 --seed 84 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta-large --batch_size 8 --accumulation_steps 12 --fold 3 --seed 94 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta-large --batch_size 8 --accumulation_steps 12 --fold 4 --seed 104 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta --batch_size 32 --accumulation_steps 3 --fold 0 --seed 14 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full 
python train.py  --model roberta --batch_size 32 --accumulation_steps 3 --fold 1 --seed 24 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta --batch_size 32 --accumulation_steps 3 --fold 2 --seed 34 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta --batch_size 32 --accumulation_steps 3 --fold 3 --seed 44 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
python train.py  --model roberta --batch_size 32 --accumulation_steps 3 --fold 4 --seed 54 --epochs 3 --beam_size 3 --devices '0' --lr 2e-5 --train_full
